import { TuningGroup } from '@/tunings/types';

const Hammerhead: TuningGroup = {
    id: 'Shotgun',
    name: 'Hammerhead',
    description: 'Shotgun',
    properties: [
        {
            default: false,
            id: 'canUseOnLadder',
            name: 'Can use on ladder?',
        },
        {
            default: false,
            id: 'canUseInWater',
            name: 'Can use in water?',
        },
        {
            default: false,
            id: 'canUseUnderWater',
            name: 'Can use under water?',
        },
        {
            default: false,
            id: 'canUseOnZipline',
            name: 'Can use on zipline?',
        },
        {
            default: false,
            id: 'dropWhenRagged',
            name: 'Drop when ragdolled?',
        },
        {
            default: false,
            id: 'hideOnRagdoll',
            name: 'Hide when ragdolled?',
        },
        {
            decimals: 2,
            default: 0.85,
            description: 'Lower = Faster, Higher = Slower',
            id: 'fireRate',
            name: 'Fire rate',
            step: 0.01,
        },
        {
            decimals: 2,
            default: -1,
            id: 'fireRecoverRate',
            name: 'Fire Recover Rate',
            step: 0.1,
        },
        {
            decimals: 2,
            default: 0,
            id: 'fireDelayTime',
            name: 'Fire Delay Time',
            step: 0.1,
        },
        {
            default: true,
            id: 'hasSemiAuto',
            name: 'Has semi auto?',
        },
        {
            default: false,
            id: 'hasFullAuto',
            name: 'Has full auto?',
        },
        {
            default: false,
            id: 'hasBurstShot',
            name: 'Has burst shot?',
        },
        {
            decimals: 0,
            default: 6,
            id: 'maxClipAmmo',
            name: 'Maximum Rounds Per Clip',
            step: 1,
        },
        {
            decimals: 1,
            default: 10,
            id: 'reloadTime',
            name: 'Reload Time',
            step: 0.1,
        },
        {
            default: false,
            id: 'autoReload',
            name: 'Auto reload?',
        },
        {
            default: false,
            id: 'reloadOnEquip',
            name: 'Reload on equip?',
        },
        {
            default: false,
            description: 'Affects weapon sway',
            name: 'Has scope?',
            id: 'hasScope',
        },
        {
            default: true,
            id: 'playGunFireEmptySound',
            name: 'Play gunfire empty sound?',
        },
        {
            default: false,
            id: 'canJumpFire',
            name: 'Can jump fire?',
        },
        {
            default: false,
            id: 'unequipOnEmpty',
            name: 'Unequip on empty?',
        },
        {
            decimals: 2,
            default: 0,
            name: 'Unequip delay',
            id: 'unequipDelay',
            step: 0.1,
        },
        {
            default: false,
            id: 'removeFromInventoryOnEmpty',
            name: 'Remove from inventory on empty?',
        },
        {
            decimals: 2,
            default: 0.5,
            id: 'equipTime',
            name: 'Equip time',
            step: 0.01,
        },
        {
            decimals: 1,
            default: 2,
            description: 'Requires "Shell Eject" to be enabled',
            name: 'Shell Speed',
            id: 'shellSpeed',
            step: 0.1,
        },
        {
            default: true,
            id: 'shellEject',
            name: 'Shell eject?',
        },
        {
            default: false,
            id: 'advancedRecoil',
            name: 'Advanced recoil?',
        },
        {
            default: false,
            id: 'hasStockRecoil',
            name: 'Has stock recoil?',
        },
        {
            decimals: 1,
            default: 5,
            id: 'stockRecoilRecoverySpeed',
            name: 'Stock Recoil Recovery Speed',
            step: 0.1,
        },
        {
            decimals: 1,
            default: 15,
            id: 'recoilBalance',
            name: 'Recoil Balance',
            step: 1,
        },
        {
            decimals: 1,
            default: 74,
            id: 'precoilBalance',
            name: 'Precoil Balance',
            step: 1,
        },
        {
            default: false,
            id: 'canFocusShot',
            name: 'Can focus shot?',
        },
        {
            default: false,
            id: 'noPrecoilZoomed',
            name: 'No precoil zoomed?',
        },
        {
            decimals: 0,
            default: 60,
            id: 'medHighEnergy',
            name: 'Medium to high energy threshold',
            step: 1,
        },
        {
            decimals: 0,
            default: 30,
            id: 'lowMedEnergy',
            name: 'Low to medium energy threshold',
            step: 1,
        },
        {
            decimals: 0,
            default: 50,
            id: 'aimDownSightsFov',
            name: 'Aim Down Sights Field Of View',
            step: 1,
        },
        {
            decimals: 0,
            default: 25,
            id: 'extraZoomingFov',
            name: 'Extra Zooming Field Of View',
            step: 1,
        },
        {
            decimals: 2,
            default: 0.52,
            id: 'shellEjectDelay',
            name: 'Shell Eject Delay',
            step: 0.1,
        },
    ],
};

export default Hammerhead;
